services:
  db:
    image: postgres:13
    container_name: calendar-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - calendar-network

volumes:
  postgres_data:

networks:
  calendar-network:
    driver: bridge
